version: '3'

services:
  vue-project:
    container_name: iOpsContainer
    build:
      context: .
      dockerfile: prod.Dockerfile
    image: vue-app
    ports:
      - 8084:80
    restart: always
